{
  "formatVersion": "1.1",
  "component": {
    "group": "org.hyperledger.fabric-chaincode-java",
    "module": "fabric-chaincode-protos",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fabric-chaincode-protos-2.4.0.jar",
          "url": "fabric-chaincode-protos-2.4.0.jar",
          "size": 852875,
          "sha512": "1883ef1a156651b7b44bdd3b105ac29d08e7c8e4b880aeb7f8e1828677855b19533efb2b235debf9f4b7f541e999e62d29333705766ebcfbf2929ab92bc6c3ea",
          "sha256": "f4eef7576733c17c797028880b9cfb6ca0f6b8813c57650743c790f9a8977fc9",
          "sha1": "7e132b0d2bccedfd175b06b2944df55f49e1a707",
          "md5": "452b168d1905183d06f15de2e46855c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.11.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.11.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded",
          "version": {
            "requires": "1.31.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.31.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.31.1"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "fabric-chaincode-protos-2.4.0.jar",
          "url": "fabric-chaincode-protos-2.4.0.jar",
          "size": 852875,
          "sha512": "1883ef1a156651b7b44bdd3b105ac29d08e7c8e4b880aeb7f8e1828677855b19533efb2b235debf9f4b7f541e999e62d29333705766ebcfbf2929ab92bc6c3ea",
          "sha256": "f4eef7576733c17c797028880b9cfb6ca0f6b8813c57650743c790f9a8977fc9",
          "sha1": "7e132b0d2bccedfd175b06b2944df55f49e1a707",
          "md5": "452b168d1905183d06f15de2e46855c9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fabric-chaincode-protos-2.4.0-javadoc.jar",
          "url": "fabric-chaincode-protos-2.4.0-javadoc.jar",
          "size": 261,
          "sha512": "9a21bb32dbbefc9bbe3b0c1c215772567eb2e14f6ed61b38f455864ed4e06a9aaf24b5ee7e4d31e27bacc16404d976cbff13c1def60b04254bd4018fd74fbf15",
          "sha256": "a1828c811594529e4ce54449ba4426dac45b0d8aeeaab0b9a30c57031f988b21",
          "sha1": "f1fb6f9bce897025095b5ab56334a2a6baa53b7f",
          "md5": "9de9081539ad84ae0d5ae4393510fcb8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fabric-chaincode-protos-2.4.0-sources.jar",
          "url": "fabric-chaincode-protos-2.4.0-sources.jar",
          "size": 177488,
          "sha512": "d941e7e686b07b40edb13e25f2f06b803c3f7b350ef19929ff57732c527d77b727994e6e18e89763800246222d96c9f75cf3a333efb511489175d2647f5db2c6",
          "sha256": "8d36da08e54dd5409018573eec924e13fd312b7c842a2f6b52ec835d689765b0",
          "sha1": "2f09e22cd1af082dede20ccb0f870fe37fbbb550",
          "md5": "4d605f31da9789b3be798c0b5535041b"
        }
      ]
    }
  ]
}
